#ifdef SIMULATION
#ifndef _KF32A13K_REG_SIMULATION_LBIST_H_
#define _KF32A13K_REG_SIMULATION_LBIST_H_
#ifdef __cplusplus
extern "C" {
#endif



//--------

#define HWIO_SCU_LBISTCTL_ADDR  0xF0036028  
#define HWIO_SCU_LBISTCTL_SCU_LBISTCTL_REQ_SHFT 0
#define HWIO_SCU_LBISTCTL_SCU_LBISTCTL_REQ_MASK 0x00000001
#define HWIO_SCU_LBISTCTL_SCU_LBISTCTL_RST_SHFT 1
#define HWIO_SCU_LBISTCTL_SCU_LBISTCTL_RST_MASK 0x00000002
#define HWIO_SCU_LBISTCTL_SCU_LBISTCTL_BODY_SHFT 2
#define HWIO_SCU_LBISTCTL_SCU_LBISTCTL_BODY_MASK 0x00000004
#define HWIO_SCU_LBISTCTL_SCU_LBISTCTL_FREQ_SHFT 4
#define HWIO_SCU_LBISTCTL_SCU_LBISTCTL_FREQ_MASK 0x000000f0
#define HWIO_SCU_LBISTCTL_SCU_LBISTCTL_ERRINJ_SHFT 30
#define HWIO_SCU_LBISTCTL_SCU_LBISTCTL_ERRINJ_MASK 0x40000000
#define HWIO_SCU_LBISTCTL_SCU_LBISTCTL_REQRED_SHFT 31
#define HWIO_SCU_LBISTCTL_SCU_LBISTCTL_REQRED_MASK 0x80000000


//--------

#define HWIO_SCU_LBISTSTA_ADDR  0xF003602C  
#define HWIO_SCU_LBISTSTA_SCU_LBISTSTA_DONE_SHFT 0
#define HWIO_SCU_LBISTSTA_SCU_LBISTSTA_DONE_MASK 0x00000001


//--------

#define HWIO_SCU_LBISTPAT_ADDR  0xF0036030  
#define HWIO_SCU_LBISTPAT_SCU_LBISTPAT_NUM_SHFT 0
#define HWIO_SCU_LBISTPAT_SCU_LBISTPAT_NUM_MASK 0x0003ffff


//--------

#define HWIO_SCU_LBISTSEED_ADDR  0xF0036034  
#define HWIO_SCU_LBISTSEED_SCU_LBISTSEED_SEED_SHFT 0
#define HWIO_SCU_LBISTSEED_SCU_LBISTSEED_SEED_MASK 0x0007ffff
#define HWIO_SCU_LBISTSEED_SCU_LBISTSEED_SPLITSH_SHFT 19
#define HWIO_SCU_LBISTSEED_SCU_LBISTSEED_SPLITSH_MASK 0x00380000


//--------

#define HWIO_SCU_LBISTSC_ADDR  0xF0036038  
#define HWIO_SCU_LBISTSC_SCU_LBISTSC_LENGTH_SHFT 0
#define HWIO_SCU_LBISTSC_SCU_LBISTSC_LENGTH_MASK 0x0000ffff


//--------

#define HWIO_SCU_LBISTSIG_ADDR  0xF003603C  
#define HWIO_SCU_LBISTSIG_SCU_LBISTSIG_SIGNATURE_SHFT 0
#define HWIO_SCU_LBISTSIG_SCU_LBISTSIG_SIGNATURE_MASK 0xffffffff


//--------

#define HWIO_RCU_STA_ADDR  0xF003612C  
#define HWIO_RCU_STA_RCU_STA_LBPORST_SHFT 27
#define HWIO_RCU_STA_RCU_STA_LBPORST_MASK 0x08000000
#define HWIO_RCU_STA_RCU_STA_LBTERM_SHFT 28
#define HWIO_RCU_STA_RCU_STA_LBTERM_MASK 0x10000000
#define HWIO_RCU_CTL1_ADDR  0xF003613C  
#define HWIO_RCU_CTL1_RCU_CTL1_COLDCLR_SHFT 1
#define HWIO_RCU_CTL1_RCU_CTL1_COLDCLR_MASK 0x00000002


#ifdef __cplusplus
}
#endif
#endif
#endif
