//****************************************************************************************
//*
//* File Name: weak_interrupt_tc1.c 
//* Project Name: FreeRTOS_13K
//* Version: v1.0
//* Date: 2024-06-03 14:42:26
//* Author: chipon
//* 
//****************************************************************************************/
//#include <KF32DA2218SQVWS.h>

//asm(".include		\"KF32DA2218SQVWS.inc\"	");	 



/* @@Important notes@@
 * When defining an interrupt, it should be confirmed that the weak definition is
 * not effective, otherwise the weak definition needs to be masked, that is, the weak
 * function under the KEEP attribute is still merged and retained
 */


/*******************************************************************************
**                      Includes                                              **
*******************************************************************************/

#include "Kfx_Ssw.h"


KFX_WEAK_INTERRUPT(default_core1_while, 1, 0);
KFX_WEAK_INTERRUPT(default_core1_while, 1, 1);
KFX_WEAK_INTERRUPT(default_core1_while, 1, 2);
KFX_WEAK_INTERRUPT(default_core1_while, 1, 3);
KFX_WEAK_INTERRUPT(default_core1_while, 1, 4);
KFX_WEAK_INTERRUPT(default_core1_while, 1, 5);
KFX_WEAK_INTERRUPT(default_core1_while, 1, 6);
KFX_WEAK_INTERRUPT(default_core1_while, 1, 7);
KFX_WEAK_INTERRUPT(default_core1_while, 1, 8);
KFX_WEAK_INTERRUPT(default_core1_while, 1, 9);
KFX_WEAK_INTERRUPT(default_core1_while, 1, 10);
KFX_WEAK_INTERRUPT(default_core1_while, 1, 11);
KFX_WEAK_INTERRUPT(default_core1_while, 1, 12);
KFX_WEAK_INTERRUPT(default_core1_while, 1, 13);
KFX_WEAK_INTERRUPT(default_core1_while, 1, 14);
KFX_WEAK_INTERRUPT(default_core1_while, 1, 15);
KFX_WEAK_INTERRUPT(default_core1_while, 1, 16);
KFX_WEAK_INTERRUPT(default_core1_while, 1, 17);
KFX_WEAK_INTERRUPT(default_core1_while, 1, 18);
KFX_WEAK_INTERRUPT(default_core1_while, 1, 19);
KFX_WEAK_INTERRUPT(default_core1_while, 1, 20);
KFX_WEAK_INTERRUPT(default_core1_while, 1, 21);
KFX_WEAK_INTERRUPT(default_core1_while, 1, 22);
KFX_WEAK_INTERRUPT(default_core1_while, 1, 23);
KFX_WEAK_INTERRUPT(default_core1_while, 1, 24);
KFX_WEAK_INTERRUPT(default_core1_while, 1, 25);
KFX_WEAK_INTERRUPT(default_core1_while, 1, 26);
KFX_WEAK_INTERRUPT(default_core1_while, 1, 27);
KFX_WEAK_INTERRUPT(default_core1_while, 1, 28);
KFX_WEAK_INTERRUPT(default_core1_while, 1, 29);
KFX_WEAK_INTERRUPT(default_core1_while, 1, 30);
KFX_WEAK_INTERRUPT(default_core1_while, 1, 31);
KFX_WEAK_INTERRUPT(default_core1_while, 1, 32);
KFX_WEAK_INTERRUPT(default_core1_while, 1, 33);
KFX_WEAK_INTERRUPT(default_core1_while, 1, 34);
KFX_WEAK_INTERRUPT(default_core1_while, 1, 35);
KFX_WEAK_INTERRUPT(default_core1_while, 1, 36);
KFX_WEAK_INTERRUPT(default_core1_while, 1, 37);
KFX_WEAK_INTERRUPT(default_core1_while, 1, 38);
KFX_WEAK_INTERRUPT(default_core1_while, 1, 39);
KFX_WEAK_INTERRUPT(default_core1_while, 1, 40);
KFX_WEAK_INTERRUPT(default_core1_while, 1, 41);
KFX_WEAK_INTERRUPT(default_core1_while, 1, 42);
KFX_WEAK_INTERRUPT(default_core1_while, 1, 43);
KFX_WEAK_INTERRUPT(default_core1_while, 1, 44);
KFX_WEAK_INTERRUPT(default_core1_while, 1, 45);
KFX_WEAK_INTERRUPT(default_core1_while, 1, 46);
KFX_WEAK_INTERRUPT(default_core1_while, 1, 47);
KFX_WEAK_INTERRUPT(default_core1_while, 1, 48);
KFX_WEAK_INTERRUPT(default_core1_while, 1, 49);
KFX_WEAK_INTERRUPT(default_core1_while, 1, 50);
KFX_WEAK_INTERRUPT(default_core1_while, 1, 51);
KFX_WEAK_INTERRUPT(default_core1_while, 1, 52);
KFX_WEAK_INTERRUPT(default_core1_while, 1, 53);
KFX_WEAK_INTERRUPT(default_core1_while, 1, 54);
KFX_WEAK_INTERRUPT(default_core1_while, 1, 55);
KFX_WEAK_INTERRUPT(default_core1_while, 1, 56);
KFX_WEAK_INTERRUPT(default_core1_while, 1, 57);
KFX_WEAK_INTERRUPT(default_core1_while, 1, 58);
KFX_WEAK_INTERRUPT(default_core1_while, 1, 59);
KFX_WEAK_INTERRUPT(default_core1_while, 1, 60);
KFX_WEAK_INTERRUPT(default_core1_while, 1, 61);
KFX_WEAK_INTERRUPT(default_core1_while, 1, 62);
KFX_WEAK_INTERRUPT(default_core1_while, 1, 63);
KFX_WEAK_INTERRUPT(default_core1_while, 1, 64);
KFX_WEAK_INTERRUPT(default_core1_while, 1, 65);
KFX_WEAK_INTERRUPT(default_core1_while, 1, 66);
KFX_WEAK_INTERRUPT(default_core1_while, 1, 67);
KFX_WEAK_INTERRUPT(default_core1_while, 1, 68);
KFX_WEAK_INTERRUPT(default_core1_while, 1, 69);
KFX_WEAK_INTERRUPT(default_core1_while, 1, 70);
KFX_WEAK_INTERRUPT(default_core1_while, 1, 71);
KFX_WEAK_INTERRUPT(default_core1_while, 1, 72);
KFX_WEAK_INTERRUPT(default_core1_while, 1, 73);
KFX_WEAK_INTERRUPT(default_core1_while, 1, 74);
KFX_WEAK_INTERRUPT(default_core1_while, 1, 75);
KFX_WEAK_INTERRUPT(default_core1_while, 1, 76);
KFX_WEAK_INTERRUPT(default_core1_while, 1, 77);
KFX_WEAK_INTERRUPT(default_core1_while, 1, 78);
KFX_WEAK_INTERRUPT(default_core1_while, 1, 79);
KFX_WEAK_INTERRUPT(default_core1_while, 1, 80);
KFX_WEAK_INTERRUPT(default_core1_while, 1, 81);
KFX_WEAK_INTERRUPT(default_core1_while, 1, 82);
KFX_WEAK_INTERRUPT(default_core1_while, 1, 83);
KFX_WEAK_INTERRUPT(default_core1_while, 1, 84);
KFX_WEAK_INTERRUPT(default_core1_while, 1, 85);
KFX_WEAK_INTERRUPT(default_core1_while, 1, 86);
KFX_WEAK_INTERRUPT(default_core1_while, 1, 87);
KFX_WEAK_INTERRUPT(default_core1_while, 1, 88);
KFX_WEAK_INTERRUPT(default_core1_while, 1, 89);
KFX_WEAK_INTERRUPT(default_core1_while, 1, 90);
KFX_WEAK_INTERRUPT(default_core1_while, 1, 91);
KFX_WEAK_INTERRUPT(default_core1_while, 1, 92);
KFX_WEAK_INTERRUPT(default_core1_while, 1, 93);
KFX_WEAK_INTERRUPT(default_core1_while, 1, 94);
KFX_WEAK_INTERRUPT(default_core1_while, 1, 95);
KFX_WEAK_INTERRUPT(default_core1_while, 1, 96);
KFX_WEAK_INTERRUPT(default_core1_while, 1, 97);
KFX_WEAK_INTERRUPT(default_core1_while, 1, 98);
KFX_WEAK_INTERRUPT(default_core1_while, 1, 99);
KFX_WEAK_INTERRUPT(default_core1_while, 1, 100);
KFX_WEAK_INTERRUPT(default_core1_while, 1, 101);
KFX_WEAK_INTERRUPT(default_core1_while, 1, 102);
KFX_WEAK_INTERRUPT(default_core1_while, 1, 103);
KFX_WEAK_INTERRUPT(default_core1_while, 1, 104);
KFX_WEAK_INTERRUPT(default_core1_while, 1, 105);
KFX_WEAK_INTERRUPT(default_core1_while, 1, 106);
KFX_WEAK_INTERRUPT(default_core1_while, 1, 107);
KFX_WEAK_INTERRUPT(default_core1_while, 1, 108);
KFX_WEAK_INTERRUPT(default_core1_while, 1, 109);
KFX_WEAK_INTERRUPT(default_core1_while, 1, 110);
KFX_WEAK_INTERRUPT(default_core1_while, 1, 111);
KFX_WEAK_INTERRUPT(default_core1_while, 1, 112);
KFX_WEAK_INTERRUPT(default_core1_while, 1, 113);
KFX_WEAK_INTERRUPT(default_core1_while, 1, 114);
KFX_WEAK_INTERRUPT(default_core1_while, 1, 115);
KFX_WEAK_INTERRUPT(default_core1_while, 1, 116);
KFX_WEAK_INTERRUPT(default_core1_while, 1, 117);
KFX_WEAK_INTERRUPT(default_core1_while, 1, 118);
KFX_WEAK_INTERRUPT(default_core1_while, 1, 119);
KFX_WEAK_INTERRUPT(default_core1_while, 1, 120);
KFX_WEAK_INTERRUPT(default_core1_while, 1, 121);
KFX_WEAK_INTERRUPT(default_core1_while, 1, 122);
KFX_WEAK_INTERRUPT(default_core1_while, 1, 123);
KFX_WEAK_INTERRUPT(default_core1_while, 1, 124);
KFX_WEAK_INTERRUPT(default_core1_while, 1, 125);
KFX_WEAK_INTERRUPT(default_core1_while, 1, 126);
KFX_WEAK_INTERRUPT(default_core1_while, 1, 127);
KFX_WEAK_INTERRUPT(default_core1_while, 1, 128);
KFX_WEAK_INTERRUPT(default_core1_while, 1, 129);
KFX_WEAK_INTERRUPT(default_core1_while, 1, 130);
KFX_WEAK_INTERRUPT(default_core1_while, 1, 131);
KFX_WEAK_INTERRUPT(default_core1_while, 1, 132);
KFX_WEAK_INTERRUPT(default_core1_while, 1, 133);
KFX_WEAK_INTERRUPT(default_core1_while, 1, 134);
KFX_WEAK_INTERRUPT(default_core1_while, 1, 135);
KFX_WEAK_INTERRUPT(default_core1_while, 1, 136);
KFX_WEAK_INTERRUPT(default_core1_while, 1, 137);
KFX_WEAK_INTERRUPT(default_core1_while, 1, 138);
KFX_WEAK_INTERRUPT(default_core1_while, 1, 139);
KFX_WEAK_INTERRUPT(default_core1_while, 1, 140);
KFX_WEAK_INTERRUPT(default_core1_while, 1, 141);
KFX_WEAK_INTERRUPT(default_core1_while, 1, 142);
KFX_WEAK_INTERRUPT(default_core1_while, 1, 143);
KFX_WEAK_INTERRUPT(default_core1_while, 1, 144);
KFX_WEAK_INTERRUPT(default_core1_while, 1, 145);
KFX_WEAK_INTERRUPT(default_core1_while, 1, 146);
KFX_WEAK_INTERRUPT(default_core1_while, 1, 147);
KFX_WEAK_INTERRUPT(default_core1_while, 1, 148);
KFX_WEAK_INTERRUPT(default_core1_while, 1, 149);
KFX_WEAK_INTERRUPT(default_core1_while, 1, 150);
KFX_WEAK_INTERRUPT(default_core1_while, 1, 151);
KFX_WEAK_INTERRUPT(default_core1_while, 1, 152);
KFX_WEAK_INTERRUPT(default_core1_while, 1, 153);
KFX_WEAK_INTERRUPT(default_core1_while, 1, 154);
KFX_WEAK_INTERRUPT(default_core1_while, 1, 155);
KFX_WEAK_INTERRUPT(default_core1_while, 1, 156);
KFX_WEAK_INTERRUPT(default_core1_while, 1, 157);
KFX_WEAK_INTERRUPT(default_core1_while, 1, 158);
KFX_WEAK_INTERRUPT(default_core1_while, 1, 159);
KFX_WEAK_INTERRUPT(default_core1_while, 1, 160);
KFX_WEAK_INTERRUPT(default_core1_while, 1, 161);
KFX_WEAK_INTERRUPT(default_core1_while, 1, 162);
KFX_WEAK_INTERRUPT(default_core1_while, 1, 163);
KFX_WEAK_INTERRUPT(default_core1_while, 1, 164);
KFX_WEAK_INTERRUPT(default_core1_while, 1, 165);
KFX_WEAK_INTERRUPT(default_core1_while, 1, 166);
KFX_WEAK_INTERRUPT(default_core1_while, 1, 167);
KFX_WEAK_INTERRUPT(default_core1_while, 1, 168);
KFX_WEAK_INTERRUPT(default_core1_while, 1, 169);
KFX_WEAK_INTERRUPT(default_core1_while, 1, 170);
KFX_WEAK_INTERRUPT(default_core1_while, 1, 171);
KFX_WEAK_INTERRUPT(default_core1_while, 1, 172);
KFX_WEAK_INTERRUPT(default_core1_while, 1, 173);
KFX_WEAK_INTERRUPT(default_core1_while, 1, 174);
KFX_WEAK_INTERRUPT(default_core1_while, 1, 175);
KFX_WEAK_INTERRUPT(default_core1_while, 1, 176);
KFX_WEAK_INTERRUPT(default_core1_while, 1, 177);
KFX_WEAK_INTERRUPT(default_core1_while, 1, 178);
KFX_WEAK_INTERRUPT(default_core1_while, 1, 179);
KFX_WEAK_INTERRUPT(default_core1_while, 1, 180);
KFX_WEAK_INTERRUPT(default_core1_while, 1, 181);
KFX_WEAK_INTERRUPT(default_core1_while, 1, 182);
KFX_WEAK_INTERRUPT(default_core1_while, 1, 183);
KFX_WEAK_INTERRUPT(default_core1_while, 1, 184);
KFX_WEAK_INTERRUPT(default_core1_while, 1, 185);
KFX_WEAK_INTERRUPT(default_core1_while, 1, 186);
KFX_WEAK_INTERRUPT(default_core1_while, 1, 187);
KFX_WEAK_INTERRUPT(default_core1_while, 1, 188);
KFX_WEAK_INTERRUPT(default_core1_while, 1, 189);
KFX_WEAK_INTERRUPT(default_core1_while, 1, 190);
KFX_WEAK_INTERRUPT(default_core1_while, 1, 191);
KFX_WEAK_INTERRUPT(default_core1_while, 1, 192);
KFX_WEAK_INTERRUPT(default_core1_while, 1, 193);
KFX_WEAK_INTERRUPT(default_core1_while, 1, 194);
KFX_WEAK_INTERRUPT(default_core1_while, 1, 195);
KFX_WEAK_INTERRUPT(default_core1_while, 1, 196);
KFX_WEAK_INTERRUPT(default_core1_while, 1, 197);
KFX_WEAK_INTERRUPT(default_core1_while, 1, 198);
KFX_WEAK_INTERRUPT(default_core1_while, 1, 199);
KFX_WEAK_INTERRUPT(default_core1_while, 1, 200);
KFX_WEAK_INTERRUPT(default_core1_while, 1, 201);
KFX_WEAK_INTERRUPT(default_core1_while, 1, 202);
KFX_WEAK_INTERRUPT(default_core1_while, 1, 203);
KFX_WEAK_INTERRUPT(default_core1_while, 1, 204);
KFX_WEAK_INTERRUPT(default_core1_while, 1, 205);
KFX_WEAK_INTERRUPT(default_core1_while, 1, 206);
KFX_WEAK_INTERRUPT(default_core1_while, 1, 207);
KFX_WEAK_INTERRUPT(default_core1_while, 1, 208);
KFX_WEAK_INTERRUPT(default_core1_while, 1, 209);
KFX_WEAK_INTERRUPT(default_core1_while, 1, 210);
KFX_WEAK_INTERRUPT(default_core1_while, 1, 211);
KFX_WEAK_INTERRUPT(default_core1_while, 1, 212);
KFX_WEAK_INTERRUPT(default_core1_while, 1, 213);
KFX_WEAK_INTERRUPT(default_core1_while, 1, 214);
KFX_WEAK_INTERRUPT(default_core1_while, 1, 215);
KFX_WEAK_INTERRUPT(default_core1_while, 1, 216);
KFX_WEAK_INTERRUPT(default_core1_while, 1, 217);
KFX_WEAK_INTERRUPT(default_core1_while, 1, 218);
KFX_WEAK_INTERRUPT(default_core1_while, 1, 219);
KFX_WEAK_INTERRUPT(default_core1_while, 1, 220);
KFX_WEAK_INTERRUPT(default_core1_while, 1, 221);
KFX_WEAK_INTERRUPT(default_core1_while, 1, 222);
KFX_WEAK_INTERRUPT(default_core1_while, 1, 223);
KFX_WEAK_INTERRUPT(default_core1_while, 1, 224);
KFX_WEAK_INTERRUPT(default_core1_while, 1, 225);
KFX_WEAK_INTERRUPT(default_core1_while, 1, 226);
KFX_WEAK_INTERRUPT(default_core1_while, 1, 227);
KFX_WEAK_INTERRUPT(default_core1_while, 1, 228);
KFX_WEAK_INTERRUPT(default_core1_while, 1, 229);
KFX_WEAK_INTERRUPT(default_core1_while, 1, 230);
KFX_WEAK_INTERRUPT(default_core1_while, 1, 231);
KFX_WEAK_INTERRUPT(default_core1_while, 1, 232);
KFX_WEAK_INTERRUPT(default_core1_while, 1, 233);
KFX_WEAK_INTERRUPT(default_core1_while, 1, 234);
KFX_WEAK_INTERRUPT(default_core1_while, 1, 235);
KFX_WEAK_INTERRUPT(default_core1_while, 1, 236);
KFX_WEAK_INTERRUPT(default_core1_while, 1, 237);
KFX_WEAK_INTERRUPT(default_core1_while, 1, 238);
KFX_WEAK_INTERRUPT(default_core1_while, 1, 239);
KFX_WEAK_INTERRUPT(default_core1_while, 1, 240);
KFX_WEAK_INTERRUPT(default_core1_while, 1, 241);
KFX_WEAK_INTERRUPT(default_core1_while, 1, 242);
KFX_WEAK_INTERRUPT(default_core1_while, 1, 243);
KFX_WEAK_INTERRUPT(default_core1_while, 1, 244);
KFX_WEAK_INTERRUPT(default_core1_while, 1, 245);
KFX_WEAK_INTERRUPT(default_core1_while, 1, 246);
KFX_WEAK_INTERRUPT(default_core1_while, 1, 247);
KFX_WEAK_INTERRUPT(default_core1_while, 1, 248);
KFX_WEAK_INTERRUPT(default_core1_while, 1, 249);
KFX_WEAK_INTERRUPT(default_core1_while, 1, 250);
KFX_WEAK_INTERRUPT(default_core1_while, 1, 251);
KFX_WEAK_INTERRUPT(default_core1_while, 1, 252);
KFX_WEAK_INTERRUPT(default_core1_while, 1, 253);
KFX_WEAK_INTERRUPT(default_core1_while, 1, 254);
KFX_WEAK_INTERRUPT(default_core1_while, 1, 255);

