//****************************************************************************************
//*
//* File Name: weak_interrupt_tc0.c 
//* Project Name: FreeRTOS_13K
//* Version: v1.0
//* Date: 2024-06-03 14:42:26
//* Author: chipon
//* 
//****************************************************************************************/
//#include <KF32DA2218SQVWS.h>

//asm(".include		\"KF32DA2218SQVWS.inc\"	");	 


/* @@Important notes@@
 * When defining an interrupt, it should be confirmed that the weak definition is
 * not effective, otherwise the weak definition needs to be masked, that is, the weak
 * function under the KEEP attribute is still merged and retained
 */


/*******************************************************************************
**                      Includes                                              **
*******************************************************************************/

#include "Kfx_Ssw.h"

KFX_WEAK_INTERRUPT(default_core0_while, 0, 0);
KFX_WEAK_INTERRUPT(default_core0_while, 0, 1);
KFX_WEAK_INTERRUPT(default_core0_while, 0, 2);
KFX_WEAK_INTERRUPT(default_core0_while, 0, 3);
KFX_WEAK_INTERRUPT(default_core0_while, 0, 4);
KFX_WEAK_INTERRUPT(default_core0_while, 0, 5);
KFX_WEAK_INTERRUPT(default_core0_while, 0, 6);
KFX_WEAK_INTERRUPT(default_core0_while, 0, 7);
KFX_WEAK_INTERRUPT(default_core0_while, 0, 8);
KFX_WEAK_INTERRUPT(default_core0_while, 0, 9);
KFX_WEAK_INTERRUPT(default_core0_while, 0, 10);
KFX_WEAK_INTERRUPT(default_core0_while, 0, 11);
KFX_WEAK_INTERRUPT(default_core0_while, 0, 12);
KFX_WEAK_INTERRUPT(default_core0_while, 0, 13);
KFX_WEAK_INTERRUPT(default_core0_while, 0, 14);
KFX_WEAK_INTERRUPT(default_core0_while, 0, 15);
KFX_WEAK_INTERRUPT(default_core0_while, 0, 16);
KFX_WEAK_INTERRUPT(default_core0_while, 0, 17);
KFX_WEAK_INTERRUPT(default_core0_while, 0, 18);
KFX_WEAK_INTERRUPT(default_core0_while, 0, 19);
KFX_WEAK_INTERRUPT(default_core0_while, 0, 20);
KFX_WEAK_INTERRUPT(default_core0_while, 0, 21);
KFX_WEAK_INTERRUPT(default_core0_while, 0, 22);
KFX_WEAK_INTERRUPT(default_core0_while, 0, 23);
KFX_WEAK_INTERRUPT(default_core0_while, 0, 24);
KFX_WEAK_INTERRUPT(default_core0_while, 0, 25);
KFX_WEAK_INTERRUPT(default_core0_while, 0, 26);
KFX_WEAK_INTERRUPT(default_core0_while, 0, 27);
KFX_WEAK_INTERRUPT(default_core0_while, 0, 28);
KFX_WEAK_INTERRUPT(default_core0_while, 0, 29);
KFX_WEAK_INTERRUPT(default_core0_while, 0, 30);
KFX_WEAK_INTERRUPT(default_core0_while, 0, 31);
KFX_WEAK_INTERRUPT(default_core0_while, 0, 32);
KFX_WEAK_INTERRUPT(default_core0_while, 0, 33);
KFX_WEAK_INTERRUPT(default_core0_while, 0, 34);
KFX_WEAK_INTERRUPT(default_core0_while, 0, 35);
KFX_WEAK_INTERRUPT(default_core0_while, 0, 36);
KFX_WEAK_INTERRUPT(default_core0_while, 0, 37);
KFX_WEAK_INTERRUPT(default_core0_while, 0, 38);
KFX_WEAK_INTERRUPT(default_core0_while, 0, 39);
KFX_WEAK_INTERRUPT(default_core0_while, 0, 40);
KFX_WEAK_INTERRUPT(default_core0_while, 0, 41);
KFX_WEAK_INTERRUPT(default_core0_while, 0, 42);
KFX_WEAK_INTERRUPT(default_core0_while, 0, 43);
KFX_WEAK_INTERRUPT(default_core0_while, 0, 44);
KFX_WEAK_INTERRUPT(default_core0_while, 0, 45);
KFX_WEAK_INTERRUPT(default_core0_while, 0, 46);
KFX_WEAK_INTERRUPT(default_core0_while, 0, 47);
KFX_WEAK_INTERRUPT(default_core0_while, 0, 48);
KFX_WEAK_INTERRUPT(default_core0_while, 0, 49);
KFX_WEAK_INTERRUPT(default_core0_while, 0, 50);
KFX_WEAK_INTERRUPT(default_core0_while, 0, 51);
KFX_WEAK_INTERRUPT(default_core0_while, 0, 52);
KFX_WEAK_INTERRUPT(default_core0_while, 0, 53);
KFX_WEAK_INTERRUPT(default_core0_while, 0, 54);
KFX_WEAK_INTERRUPT(default_core0_while, 0, 55);
KFX_WEAK_INTERRUPT(default_core0_while, 0, 56);
KFX_WEAK_INTERRUPT(default_core0_while, 0, 57);
KFX_WEAK_INTERRUPT(default_core0_while, 0, 58);
KFX_WEAK_INTERRUPT(default_core0_while, 0, 59);
KFX_WEAK_INTERRUPT(default_core0_while, 0, 60);
KFX_WEAK_INTERRUPT(default_core0_while, 0, 61);
KFX_WEAK_INTERRUPT(default_core0_while, 0, 62);
KFX_WEAK_INTERRUPT(default_core0_while, 0, 63);
KFX_WEAK_INTERRUPT(default_core0_while, 0, 64);
KFX_WEAK_INTERRUPT(default_core0_while, 0, 65);
KFX_WEAK_INTERRUPT(default_core0_while, 0, 66);
KFX_WEAK_INTERRUPT(default_core0_while, 0, 67);
KFX_WEAK_INTERRUPT(default_core0_while, 0, 68);
KFX_WEAK_INTERRUPT(default_core0_while, 0, 69);
KFX_WEAK_INTERRUPT(default_core0_while, 0, 70);
KFX_WEAK_INTERRUPT(default_core0_while, 0, 71);
KFX_WEAK_INTERRUPT(default_core0_while, 0, 72);
KFX_WEAK_INTERRUPT(default_core0_while, 0, 73);
KFX_WEAK_INTERRUPT(default_core0_while, 0, 74);
KFX_WEAK_INTERRUPT(default_core0_while, 0, 75);
KFX_WEAK_INTERRUPT(default_core0_while, 0, 76);
KFX_WEAK_INTERRUPT(default_core0_while, 0, 77);
KFX_WEAK_INTERRUPT(default_core0_while, 0, 78);
KFX_WEAK_INTERRUPT(default_core0_while, 0, 79);
KFX_WEAK_INTERRUPT(default_core0_while, 0, 80);
KFX_WEAK_INTERRUPT(default_core0_while, 0, 81);
KFX_WEAK_INTERRUPT(default_core0_while, 0, 82);
KFX_WEAK_INTERRUPT(default_core0_while, 0, 83);
KFX_WEAK_INTERRUPT(default_core0_while, 0, 84);
KFX_WEAK_INTERRUPT(default_core0_while, 0, 85);
KFX_WEAK_INTERRUPT(default_core0_while, 0, 86);
KFX_WEAK_INTERRUPT(default_core0_while, 0, 87);
KFX_WEAK_INTERRUPT(default_core0_while, 0, 88);
KFX_WEAK_INTERRUPT(default_core0_while, 0, 89);
KFX_WEAK_INTERRUPT(default_core0_while, 0, 90);
KFX_WEAK_INTERRUPT(default_core0_while, 0, 91);
KFX_WEAK_INTERRUPT(default_core0_while, 0, 92);
KFX_WEAK_INTERRUPT(default_core0_while, 0, 93);
KFX_WEAK_INTERRUPT(default_core0_while, 0, 94);
KFX_WEAK_INTERRUPT(default_core0_while, 0, 95);
KFX_WEAK_INTERRUPT(default_core0_while, 0, 96);
KFX_WEAK_INTERRUPT(default_core0_while, 0, 97);
KFX_WEAK_INTERRUPT(default_core0_while, 0, 98);
KFX_WEAK_INTERRUPT(default_core0_while, 0, 99);
KFX_WEAK_INTERRUPT(default_core0_while, 0, 100);
KFX_WEAK_INTERRUPT(default_core0_while, 0, 101);
KFX_WEAK_INTERRUPT(default_core0_while, 0, 102);
KFX_WEAK_INTERRUPT(default_core0_while, 0, 103);
KFX_WEAK_INTERRUPT(default_core0_while, 0, 104);
KFX_WEAK_INTERRUPT(default_core0_while, 0, 105);
KFX_WEAK_INTERRUPT(default_core0_while, 0, 106);
KFX_WEAK_INTERRUPT(default_core0_while, 0, 107);
KFX_WEAK_INTERRUPT(default_core0_while, 0, 108);
KFX_WEAK_INTERRUPT(default_core0_while, 0, 109);
KFX_WEAK_INTERRUPT(default_core0_while, 0, 110);
KFX_WEAK_INTERRUPT(default_core0_while, 0, 111);
KFX_WEAK_INTERRUPT(default_core0_while, 0, 112);
KFX_WEAK_INTERRUPT(default_core0_while, 0, 113);
KFX_WEAK_INTERRUPT(default_core0_while, 0, 114);
KFX_WEAK_INTERRUPT(default_core0_while, 0, 115);
KFX_WEAK_INTERRUPT(default_core0_while, 0, 116);
KFX_WEAK_INTERRUPT(default_core0_while, 0, 117);
KFX_WEAK_INTERRUPT(default_core0_while, 0, 118);
KFX_WEAK_INTERRUPT(default_core0_while, 0, 119);
KFX_WEAK_INTERRUPT(default_core0_while, 0, 120);
KFX_WEAK_INTERRUPT(default_core0_while, 0, 121);
KFX_WEAK_INTERRUPT(default_core0_while, 0, 122);
KFX_WEAK_INTERRUPT(default_core0_while, 0, 123);
KFX_WEAK_INTERRUPT(default_core0_while, 0, 124);
KFX_WEAK_INTERRUPT(default_core0_while, 0, 125);
KFX_WEAK_INTERRUPT(default_core0_while, 0, 126);
KFX_WEAK_INTERRUPT(default_core0_while, 0, 127);
KFX_WEAK_INTERRUPT(default_core0_while, 0, 128);
KFX_WEAK_INTERRUPT(default_core0_while, 0, 129);
KFX_WEAK_INTERRUPT(default_core0_while, 0, 130);
KFX_WEAK_INTERRUPT(default_core0_while, 0, 131);
KFX_WEAK_INTERRUPT(default_core0_while, 0, 132);
KFX_WEAK_INTERRUPT(default_core0_while, 0, 133);
KFX_WEAK_INTERRUPT(default_core0_while, 0, 134);
KFX_WEAK_INTERRUPT(default_core0_while, 0, 135);
KFX_WEAK_INTERRUPT(default_core0_while, 0, 136);
KFX_WEAK_INTERRUPT(default_core0_while, 0, 137);
KFX_WEAK_INTERRUPT(default_core0_while, 0, 138);
KFX_WEAK_INTERRUPT(default_core0_while, 0, 139);
KFX_WEAK_INTERRUPT(default_core0_while, 0, 140);
KFX_WEAK_INTERRUPT(default_core0_while, 0, 141);
KFX_WEAK_INTERRUPT(default_core0_while, 0, 142);
KFX_WEAK_INTERRUPT(default_core0_while, 0, 143);
KFX_WEAK_INTERRUPT(default_core0_while, 0, 144);
KFX_WEAK_INTERRUPT(default_core0_while, 0, 145);
KFX_WEAK_INTERRUPT(default_core0_while, 0, 146);
KFX_WEAK_INTERRUPT(default_core0_while, 0, 147);
KFX_WEAK_INTERRUPT(default_core0_while, 0, 148);
KFX_WEAK_INTERRUPT(default_core0_while, 0, 149);
KFX_WEAK_INTERRUPT(default_core0_while, 0, 150);
KFX_WEAK_INTERRUPT(default_core0_while, 0, 151);
KFX_WEAK_INTERRUPT(default_core0_while, 0, 152);
KFX_WEAK_INTERRUPT(default_core0_while, 0, 153);
KFX_WEAK_INTERRUPT(default_core0_while, 0, 154);
KFX_WEAK_INTERRUPT(default_core0_while, 0, 155);
KFX_WEAK_INTERRUPT(default_core0_while, 0, 156);
KFX_WEAK_INTERRUPT(default_core0_while, 0, 157);
KFX_WEAK_INTERRUPT(default_core0_while, 0, 158);
KFX_WEAK_INTERRUPT(default_core0_while, 0, 159);
KFX_WEAK_INTERRUPT(default_core0_while, 0, 160);
KFX_WEAK_INTERRUPT(default_core0_while, 0, 161);
KFX_WEAK_INTERRUPT(default_core0_while, 0, 162);
KFX_WEAK_INTERRUPT(default_core0_while, 0, 163);
KFX_WEAK_INTERRUPT(default_core0_while, 0, 164);
KFX_WEAK_INTERRUPT(default_core0_while, 0, 165);
KFX_WEAK_INTERRUPT(default_core0_while, 0, 166);
KFX_WEAK_INTERRUPT(default_core0_while, 0, 167);
KFX_WEAK_INTERRUPT(default_core0_while, 0, 168);
KFX_WEAK_INTERRUPT(default_core0_while, 0, 169);
KFX_WEAK_INTERRUPT(default_core0_while, 0, 170);
KFX_WEAK_INTERRUPT(default_core0_while, 0, 171);
KFX_WEAK_INTERRUPT(default_core0_while, 0, 172);
KFX_WEAK_INTERRUPT(default_core0_while, 0, 173);
KFX_WEAK_INTERRUPT(default_core0_while, 0, 174);
KFX_WEAK_INTERRUPT(default_core0_while, 0, 175);
KFX_WEAK_INTERRUPT(default_core0_while, 0, 176);
KFX_WEAK_INTERRUPT(default_core0_while, 0, 177);
KFX_WEAK_INTERRUPT(default_core0_while, 0, 178);
KFX_WEAK_INTERRUPT(default_core0_while, 0, 179);
KFX_WEAK_INTERRUPT(default_core0_while, 0, 180);
KFX_WEAK_INTERRUPT(default_core0_while, 0, 181);
KFX_WEAK_INTERRUPT(default_core0_while, 0, 182);
KFX_WEAK_INTERRUPT(default_core0_while, 0, 183);
KFX_WEAK_INTERRUPT(default_core0_while, 0, 184);
KFX_WEAK_INTERRUPT(default_core0_while, 0, 185);
KFX_WEAK_INTERRUPT(default_core0_while, 0, 186);
KFX_WEAK_INTERRUPT(default_core0_while, 0, 187);
KFX_WEAK_INTERRUPT(default_core0_while, 0, 188);
KFX_WEAK_INTERRUPT(default_core0_while, 0, 189);
KFX_WEAK_INTERRUPT(default_core0_while, 0, 190);
KFX_WEAK_INTERRUPT(default_core0_while, 0, 191);
KFX_WEAK_INTERRUPT(default_core0_while, 0, 192);
KFX_WEAK_INTERRUPT(default_core0_while, 0, 193);
KFX_WEAK_INTERRUPT(default_core0_while, 0, 194);
KFX_WEAK_INTERRUPT(default_core0_while, 0, 195);
KFX_WEAK_INTERRUPT(default_core0_while, 0, 196);
KFX_WEAK_INTERRUPT(default_core0_while, 0, 197);
KFX_WEAK_INTERRUPT(default_core0_while, 0, 198);
KFX_WEAK_INTERRUPT(default_core0_while, 0, 199);
KFX_WEAK_INTERRUPT(default_core0_while, 0, 200);
KFX_WEAK_INTERRUPT(default_core0_while, 0, 201);
KFX_WEAK_INTERRUPT(default_core0_while, 0, 202);
KFX_WEAK_INTERRUPT(default_core0_while, 0, 203);
KFX_WEAK_INTERRUPT(default_core0_while, 0, 204);
KFX_WEAK_INTERRUPT(default_core0_while, 0, 205);
KFX_WEAK_INTERRUPT(default_core0_while, 0, 206);
KFX_WEAK_INTERRUPT(default_core0_while, 0, 207);
KFX_WEAK_INTERRUPT(default_core0_while, 0, 208);
KFX_WEAK_INTERRUPT(default_core0_while, 0, 209);
KFX_WEAK_INTERRUPT(default_core0_while, 0, 210);
KFX_WEAK_INTERRUPT(default_core0_while, 0, 211);
KFX_WEAK_INTERRUPT(default_core0_while, 0, 212);
KFX_WEAK_INTERRUPT(default_core0_while, 0, 213);
KFX_WEAK_INTERRUPT(default_core0_while, 0, 214);
KFX_WEAK_INTERRUPT(default_core0_while, 0, 215);
KFX_WEAK_INTERRUPT(default_core0_while, 0, 216);
KFX_WEAK_INTERRUPT(default_core0_while, 0, 217);
KFX_WEAK_INTERRUPT(default_core0_while, 0, 218);
KFX_WEAK_INTERRUPT(default_core0_while, 0, 219);
KFX_WEAK_INTERRUPT(default_core0_while, 0, 220);
KFX_WEAK_INTERRUPT(default_core0_while, 0, 221);
KFX_WEAK_INTERRUPT(default_core0_while, 0, 222);
KFX_WEAK_INTERRUPT(default_core0_while, 0, 223);
KFX_WEAK_INTERRUPT(default_core0_while, 0, 224);
KFX_WEAK_INTERRUPT(default_core0_while, 0, 225);
KFX_WEAK_INTERRUPT(default_core0_while, 0, 226);
KFX_WEAK_INTERRUPT(default_core0_while, 0, 227);
KFX_WEAK_INTERRUPT(default_core0_while, 0, 228);
KFX_WEAK_INTERRUPT(default_core0_while, 0, 229);
KFX_WEAK_INTERRUPT(default_core0_while, 0, 230);
KFX_WEAK_INTERRUPT(default_core0_while, 0, 231);
KFX_WEAK_INTERRUPT(default_core0_while, 0, 232);
KFX_WEAK_INTERRUPT(default_core0_while, 0, 233);
KFX_WEAK_INTERRUPT(default_core0_while, 0, 234);
KFX_WEAK_INTERRUPT(default_core0_while, 0, 235);
KFX_WEAK_INTERRUPT(default_core0_while, 0, 236);
KFX_WEAK_INTERRUPT(default_core0_while, 0, 237);
KFX_WEAK_INTERRUPT(default_core0_while, 0, 238);
KFX_WEAK_INTERRUPT(default_core0_while, 0, 239);
KFX_WEAK_INTERRUPT(default_core0_while, 0, 240);
KFX_WEAK_INTERRUPT(default_core0_while, 0, 241);
KFX_WEAK_INTERRUPT(default_core0_while, 0, 242);
KFX_WEAK_INTERRUPT(default_core0_while, 0, 243);
KFX_WEAK_INTERRUPT(default_core0_while, 0, 244);
KFX_WEAK_INTERRUPT(default_core0_while, 0, 245);
KFX_WEAK_INTERRUPT(default_core0_while, 0, 246);
KFX_WEAK_INTERRUPT(default_core0_while, 0, 247);
KFX_WEAK_INTERRUPT(default_core0_while, 0, 248);
KFX_WEAK_INTERRUPT(default_core0_while, 0, 249);
KFX_WEAK_INTERRUPT(default_core0_while, 0, 250);
KFX_WEAK_INTERRUPT(default_core0_while, 0, 251);
KFX_WEAK_INTERRUPT(default_core0_while, 0, 252);
KFX_WEAK_INTERRUPT(default_core0_while, 0, 253);
KFX_WEAK_INTERRUPT(default_core0_while, 0, 254);
KFX_WEAK_INTERRUPT(default_core0_while, 0, 255);


